/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AudioPlayer: typeof import('./src/components/AudioPlayer.vue')['default']
    AudioPlaylist: typeof import('./src/components/AudioPlaylist.vue')['default']
    ComicViewer: typeof import('./src/components/ComicViewer.vue')['default']
    FileContextMenu: typeof import('./src/components/FileContextMenu.vue')['default']
    FileDetailDrawer: typeof import('./src/components/FileDetailDrawer.vue')['default']
    FileExplorer: typeof import('./src/components/FileExplorer.vue')['default']
    FileGridView: typeof import('./src/components/FileGridView.vue')['default']
    FileListView: typeof import('./src/components/FileListView.vue')['default']
    FilePanel: typeof import('./src/components/FilePanel.vue')['default']
    FilePreview: typeof import('./src/components/FilePreview.vue')['default']
    FileUpload: typeof import('./src/components/FileUpload.vue')['default']
    FolderPicker: typeof import('./src/components/FolderPicker.vue')['default']
    PdfViewer: typeof import('./src/components/PdfViewer.vue')['default']
    PeerList: typeof import('./src/components/PeerList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TAlert: typeof import('tdesign-vue-next')['Alert']
    TBadge: typeof import('tdesign-vue-next')['Badge']
    TBreadcrumb: typeof import('tdesign-vue-next')['Breadcrumb']
    TBreadcrumbItem: typeof import('tdesign-vue-next')['BreadcrumbItem']
    TButton: typeof import('tdesign-vue-next')['Button']
    TConfigProvider: typeof import('tdesign-vue-next')['ConfigProvider']
    TDescriptions: typeof import('tdesign-vue-next')['Descriptions']
    TDescriptionsItem: typeof import('tdesign-vue-next')['DescriptionsItem']
    TDialog: typeof import('tdesign-vue-next')['Dialog']
    TDivider: typeof import('tdesign-vue-next')['Divider']
    TDrawer: typeof import('tdesign-vue-next')['Drawer']
    TDropdown: typeof import('tdesign-vue-next')['Dropdown']
    TextViewer: typeof import('./src/components/TextViewer.vue')['default']
    TIcon: typeof import('tdesign-vue-next')['Icon']
    TInput: typeof import('tdesign-vue-next')['Input']
    TInputNumber: typeof import('tdesign-vue-next')['InputNumber']
    TLoading: typeof import('tdesign-vue-next')['Loading']
    TProgress: typeof import('tdesign-vue-next')['Progress']
    TransferTaskItem: typeof import('./src/components/TransferTaskItem.vue')['default']
    TSelect: typeof import('tdesign-vue-next')['Select']
    TSlider: typeof import('tdesign-vue-next')['Slider']
    TSpace: typeof import('tdesign-vue-next')['Space']
    TTabPanel: typeof import('tdesign-vue-next')['TabPanel']
    TTabs: typeof import('tdesign-vue-next')['Tabs']
    VideoPlayer: typeof import('./src/components/VideoPlayer.vue')['default']
    VideoPlaylistPanel: typeof import('./src/components/VideoPlaylistPanel.vue')['default']
  }
}
