package handlers

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"tea-cloud/backend/services"
)

// ThumbnailHandler serves video thumbnails generated by ffmpeg.
type ThumbnailHandler struct {
	svc *services.ThumbnailService
}

func NewThumbnailHandler(svc *services.ThumbnailService) *ThumbnailHandler {
	return &ThumbnailHandler{svc: svc}
}

// GetThumbnail godoc
// GET /api/files/thumbnail?path=
// Returns a JPEG thumbnail for the given video file.
// Returns 404 if ffmpeg is unavailable, the file is not a video, or extraction fails.
func (h *ThumbnailHandler) GetThumbnail(c *gin.Context) {
	relPath := c.Query("path")
	if relPath == "" {
		c.JSON(http.StatusBadRequest, gin.H{"error": "path required"})
		return
	}

	data, err := h.svc.Generate(relPath)
	if err != nil {
		c.Status(http.StatusNotFound)
		return
	}

	c.Header("Cache-Control", "public, max-age=86400")
	c.Data(http.StatusOK, "image/jpeg", data)
}
